apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-loadtest-v1
  namespace: namespace1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: locust-loadtest-v1
  template:
    metadata:
      labels:
        app: locust-loadtest-v1
    spec:
      containers:
      - name: locust-loadtest-v1
        image: charliemun/locust-loadtest:v1.0.2
        # imagePullPolicy: Always
        # ports:
        # - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: locust-entrypoint-v1
  namespace: namespace1
spec:
  type: NodePort
  selector:
    app: locust-loadtest-v1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001