apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-loadtest
  namespace: locust-loadtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-loadtest
  template:
    metadata:
      labels:
        app: locust-loadtest
    spec:
      containers:
      - name: locust-loadtest
        image: charliemun/locust-loadtest:v1.0.0
        # imagePullPolicy: Always
        # ports:
        # - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: locust-entrypoint
  namespace: locust-loadtest
spec:
  type: NodePort
  selector:
    app: locust-loadtest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003